class CfgPatches
{
	class FMS_Bars
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Scripts"
		};
	};
};
class CfgVehicles
{
	class FreezeBar_base;
	class FreezeBar_Bronze_Flawed: FreezeBar_base
	{
		scope=2;
		displayName="有瑕疵的青铜融合棒";
		descriptionShort="T1融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier1_Bars\FreezeBar_Bronze_Flawed.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Steel_Flawed: FreezeBar_base
	{
		scope=2;
		displayName="有瑕疵的钢铁融合棒";
		descriptionShort="T1融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier1_Bars\FreezeBar_Steel_Flawed.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Composite_Flawed: FreezeBar_base
	{
		scope=2;
		displayName="有瑕疵的复合融合棒";
		descriptionShort="T1融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier1_Bars\FreezeBar_Composite_Flawed.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Crystal_Flawed: FreezeBar_base
	{
		scope=2;
		displayName="有瑕疵的水晶融合棒";
		descriptionShort="T1融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier1_Bars\FreezeBar_Crystal_Flawed.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Electrum_Flawed: FreezeBar_base
	{
		scope=2;
		displayName="有瑕疵的金银合金融合棒";
		descriptionShort="T1融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier1_Bars\FreezeBar_Electrum_Flawed.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Prismatic_Flawed: FreezeBar_base
	{
		scope=2;
		displayName="有瑕疵的棱镜融合棒";
		descriptionShort="T1融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier1_Bars\FreezeBar_Prismatic_Flawed.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Ruby_Flawed: FreezeBar_base
	{
		scope=2;
		displayName="有瑕疵的红宝石融合棒";
		descriptionShort="T1融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier1_Bars\FreezeBar_Ruby_Flawed.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Void_Flawed: FreezeBar_base
	{
		scope=2;
		displayName="有瑕疵的虚空融合棒";
		descriptionShort="T1融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier1_Bars\FreezeBar_Void_Flawed.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Bronze_Standard: FreezeBar_base
	{
		scope=2;
		displayName="标准的青铜融合棒";
		descriptionShort="T2融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier2_Bars\FreezeBar_Bronze_Standard.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Composite_Standard: FreezeBar_base
	{
		scope=2;
		displayName="标准的复合融合棒";
		descriptionShort="T2融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier2_Bars\FreezeBar_Composite_Standard.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Crystal_Standard: FreezeBar_base
	{
		scope=2;
		displayName="标准的水晶融合棒";
		descriptionShort="T2融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier2_Bars\FreezeBar_Crystal_Standard.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Electrum_Standard: FreezeBar_base
	{
		scope=2;
		displayName="标准的金银合金融合棒";
		descriptionShort="T2融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier2_Bars\FreezeBar_Electrum_Standard.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Prismatic_Standard: FreezeBar_base
	{
		scope=2;
		displayName="标准的棱镜融合棒";
		descriptionShort="T2融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier2_Bars\FreezeBar_Prismatic_Standard.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Ruby_Standard: FreezeBar_base
	{
		scope=2;
		displayName="标准的红宝石融合棒";
		descriptionShort="T2融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier2_Bars\FreezeBar_Ruby_Standard.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Steel_Standard: FreezeBar_base
	{
		scope=2;
		displayName="标准的钢铁融合棒";
		descriptionShort="T2融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier2_Bars\FreezeBar_Steel_Standard.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Void_Standard: FreezeBar_base
	{
		scope=2;
		displayName="标准的虚空融合棒";
		descriptionShort="T2融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier2_Bars\FreezeBar_Void_Standard.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Bronze_Perfect: FreezeBar_base
	{
		scope=2;
		displayName="完美的青铜融合棒";
		descriptionShort="T3融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier3_Bars\FreezeBar_Bronze_Perfect.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Composite_Perfect: FreezeBar_base
	{
		scope=2;
		displayName="完美的复合融合棒";
		descriptionShort="T3融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier3_Bars\FreezeBar_Composite_Perfect.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Crystal_Perfect: FreezeBar_base
	{
		scope=2;
		displayName="完美的水晶融合棒";
		descriptionShort="T3融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier3_Bars\FreezeBar_Crystal_Perfect.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Electrum_Perfect: FreezeBar_base
	{
		scope=2;
		displayName="完美的金银合金融合棒";
		descriptionShort="T3融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier3_Bars\FreezeBar_Electrum_Perfect.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Prismatic_Perfect: FreezeBar_base
	{
		scope=2;
		displayName="完美的棱镜融合棒";
		descriptionShort="T3融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier3_Bars\FreezeBar_Prismatic_Perfect.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Ruby_Perfect: FreezeBar_base
	{
		scope=2;
		displayName="完美的红宝石融合棒";
		descriptionShort="T3融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier3_Bars\FreezeBar_Ruby_Perfect.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Steel_Perfect: FreezeBar_base
	{
		scope=2;
		displayName="完美的钢铁融合棒";
		descriptionShort="T3融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier3_Bars\FreezeBar_Steel_Perfect.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Void_Perfect: FreezeBar_base
	{
		scope=2;
		displayName="完美的虚空融合棒";
		descriptionShort="T3融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier3_Bars\FreezeBar_Void_Perfect.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Ascendant: FreezeBar_base
	{
		scope=2;
		displayName="超凡融合棒";
		descriptionShort="T4融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier4_Bars\FreezeBar_Ascendant.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Titanforge: FreezeBar_base
	{
		scope=2;
		displayName="泰坦锻造融合棒";
		descriptionShort="T4融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier4_Bars\FreezeBar_Titanforge.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Infinity: FreezeBar_base
	{
		scope=2;
		displayName="无限融合棒";
		descriptionShort="T4融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier4_Bars\FreezeBar_Infinity.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Celestial: FreezeBar_base
	{
		scope=2;
		displayName="天体融合棒";
		descriptionShort="T4融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier4_Bars\FreezeBar_Celestial.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Voidsteel: FreezeBar_base
	{
		scope=2;
		displayName="虚空钢融合棒";
		descriptionShort="T5融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier5_Bars\FreezeBar_Voidsteel.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Bloodmetal: FreezeBar_base
	{
		scope=2;
		displayName="血金属融合棒";
		descriptionShort="T5融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier5_Bars\FreezeBar_Bloodmetal.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
	class FreezeBar_Nexus: FreezeBar_base
	{
		scope=2;
		displayName="枢纽融合棒";
		descriptionShort="T6融合棒。DayZ挖矿系统使用。";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\Data\FMS_Bar.p3d";
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Bars\FMS_Bars_MiniGame\FMS_Tier6_Bars\FreezeBar_Nexus.paa"
		};
		hiddenSelections[]=
		{
			"barcamo"
		};
	};
};
