class CfgPatches
{
	class FMS_Gems_Cut
	{
		units[]=
		{
			"FreezeGem_Jade_Cut",
			"FreezeGem_Amber_Cut",
			"FreezeGem_Iolite_Cut",
			"FreezeGem_Amethyst_Cut",
			"FreezeGem_Aquamarine_Cut",
			"FreezeGem_Ruby_Cut",
			"FreezeGem_Turquoise_Cut",
			"FreezeGem_FancyColourDiamond_Cut"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Gear_Consumables",
			"FreezeGem_Base"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	class FreezeGem_Base;
	class FreezeGem_Jade_Cut: FreezeGem_Base
	{
		scope=2;
		displayName="切割翡翠";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		descriptionShort="在磨石上切割的宝石。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Jade_cut.paa"
		};
	};
	class FreezeGem_Amber_Cut: FreezeGem_Base
	{
		scope=2;
		displayName="切割琥珀宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		descriptionShort="在磨石上切割的宝石。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Amber_cut.paa"
		};
	};
	class FreezeGem_Iolite_Cut: FreezeGem_Base
	{
		scope=2;
		displayName="切割堇青石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		descriptionShort="在磨石上切割的宝石。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Iolite_cut.paa"
		};
	};
	class FreezeGem_Amethyst_Cut: FreezeGem_Base
	{
		scope=2;
		displayName="切割紫水晶";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		descriptionShort="在磨石上切割的宝石。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Amethyst_cut.paa"
		};
	};
	class FreezeGem_Aquamarine_Cut: FreezeGem_Base
	{
		scope=2;
		displayName="切割海蓝宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		descriptionShort="在磨石上切割的宝石。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Aquamarine_cut.paa"
		};
	};
	class FreezeGem_Ruby_Cut: FreezeGem_Base
	{
		scope=2;
		displayName="切割红宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		descriptionShort="在磨石上切割的宝石。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Ruby_cut.paa"
		};
	};
	class FreezeGem_Turquoise_Cut: FreezeGem_Base
	{
		scope=2;
		displayName="切割绿松石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		descriptionShort="在磨石上切割的宝石。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Turquoise_cut.paa"
		};
	};
	class FreezeGem_FancyColourDiamond_Cut: FreezeGem_Base
	{
		scope=2;
		displayName="切割彩色钻石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		descriptionShort="在磨石上切割的宝石。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gems_FancyColourDiamond_cut.paa"
		};
	};
	class FreezeProp_CutJade: HouseNoDestruct
	{
		scope=1;
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Jade_cut.paa"
		};
	};
	class FreezeProp_CutAmethyst: HouseNoDestruct
	{
		scope=1;
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Amethyst_cut.paa"
		};
	};
	class FreezeProp_CutAquamarine: HouseNoDestruct
	{
		scope=1;
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Aquamarine_cut.paa"
		};
	};
	class FreezeProp_CutAmber: HouseNoDestruct
	{
		scope=1;
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Amber_cut.paa"
		};
	};
	class FreezeProp_CutFancyColourDiamond: HouseNoDestruct
	{
		scope=1;
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gems_FancyColourDiamond_cut.paa"
		};
	};
	class FreezeProp_CutIolite: HouseNoDestruct
	{
		scope=1;
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Iolite_cut.paa"
		};
	};
	class FreezeProp_CutRuby: HouseNoDestruct
	{
		scope=1;
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Ruby_cut.paa"
		};
	};
	class FreezeProp_CutTurquoise: HouseNoDestruct
	{
		scope=1;
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\FMS_Gems_Cut.p3d";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Cut\Textures_Cut\FMS_Gem_Turquoise_cut.paa"
		};
	};
};
