class CfgPatches
{
	class FMS_Gems_Flawed
	{
		units[]=
		{
			"FreezeGem_Jade_Flawed",
			"FreezeGem_Amber_Flawed",
			"FreezeGem_Iolite_Flawed",
			"FreezeGem_Amethyst_Flawed",
			"FreezeGem_Aquamarine_Flawed",
			"FreezeGem_Ruby_Flawed",
			"FreezeGem_Turquoise_Flawed",
			"FreezeGem_FancyColourDiamond_Flawed"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Data",
			"DZ_Gear_Consumables",
			"FreezeGem_Base"
		};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	class FreezeGem_Base;
	class FreezeGem_Jade_Flawed: FreezeGem_Base
	{
		scope=2;
		displayName="有瑕疵的翡翠宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Flawed_Gem_Flawed.p3d";
		descriptionShort="在磨石上切割的宝石。DayZ挖矿系统使用。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Textures_Flawed\FMS_Gem_Jade_Flawed.paa"
		};
		canBeSplit=1;
		varStackMax=100;
		varQuantityDestroyOnMin=1;
		varQuantityInit=1;
		varQuantityMin=0;
		varQuantityMax=100;
	};
	class FreezeGem_Amber_Flawed: FreezeGem_Base
	{
		scope=2;
		displayName="有瑕疵的琥珀宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Flawed_Gem_Flawed.p3d";
		descriptionShort="在磨石上切割的宝石。DayZ挖矿系统使用。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Textures_Flawed\FMS_Gem_Amber_Flawed.paa"
		};
		canBeSplit=1;
		varStackMax=100;
		varQuantityDestroyOnMin=1;
		varQuantityInit=1;
		varQuantityMin=0;
		varQuantityMax=100;
	};
	class FreezeGem_Iolite_Flawed: FreezeGem_Base
	{
		scope=2;
		displayName="有瑕疵的堇青石宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Flawed_Gem_Flawed.p3d";
		descriptionShort="在磨石上切割的宝石。DayZ挖矿系统使用。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Textures_Flawed\FMS_Gem_Iolite_Flawed.paa"
		};
		canBeSplit=1;
		varStackMax=100;
		varQuantityDestroyOnMin=1;
		varQuantityInit=1;
		varQuantityMin=0;
		varQuantityMax=100;
	};
	class FreezeGem_Amethyst_Flawed: FreezeGem_Base
	{
		scope=2;
		displayName="有瑕疵的紫水晶宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Flawed_Gem_Flawed.p3d";
		descriptionShort="在磨石上切割的宝石。DayZ挖矿系统使用。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Textures_Flawed\FMS_Gem_Amethyst_Flawed.paa"
		};
		canBeSplit=1;
		varStackMax=100;
		varQuantityDestroyOnMin=1;
		varQuantityInit=1;
		varQuantityMin=0;
		varQuantityMax=100;
	};
	class FreezeGem_Aquamarine_Flawed: FreezeGem_Base
	{
		scope=2;
		displayName="有瑕疵的海蓝宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Flawed_Gem_Flawed.p3d";
		descriptionShort="在磨石上切割的宝石。DayZ挖矿系统使用。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Textures_Flawed\FMS_Gem_Aquamarine_Flawed.paa"
		};
		canBeSplit=1;
		varStackMax=100;
		varQuantityDestroyOnMin=1;
		varQuantityInit=1;
		varQuantityMin=0;
		varQuantityMax=100;
	};
	class FreezeGem_Ruby_Flawed: FreezeGem_Base
	{
		scope=2;
		displayName="有瑕疵的红宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Flawed_Gem_Flawed.p3d";
		descriptionShort="在磨石上切割的宝石。DayZ挖矿系统使用。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Textures_Flawed\FMS_Gem_Ruby_Flawed.paa"
		};
		canBeSplit=1;
		varStackMax=100;
		varQuantityDestroyOnMin=1;
		varQuantityInit=1;
		varQuantityMin=0;
		varQuantityMax=100;
	};
	class FreezeGem_Turquoise_Flawed: FreezeGem_Base
	{
		scope=2;
		displayName="有瑕疵的绿松石宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Flawed_Gem_Flawed.p3d";
		descriptionShort="在磨石上切割的宝石。DayZ挖矿系统使用。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Textures_Flawed\FMS_Gem_Turquoise_Flawed.paa"
		};
		canBeSplit=1;
		varStackMax=100;
		varQuantityDestroyOnMin=1;
		varQuantityInit=1;
		varQuantityMin=0;
		varQuantityMax=100;
	};
	class FreezeGem_FancyColourDiamond_Flawed: FreezeGem_Base
	{
		scope=2;
		displayName="有瑕疵的彩色钻石宝石";
		model="MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Flawed_Gem_Flawed.p3d";
		descriptionShort="在磨石上切割的宝石。DayZ挖矿系统使用。";
		hiddenSelections[]=
		{
			"gem"
		};
		hiddenSelectionsTextures[]=
		{
			"MrfreezeMiningSystemV2\FMS_Data\FMS_Gems\FMS_Gems_Flawed\Textures_Flawed\FMS_Gems_FancyColourDiamond_Flawed.paa"
		};
		canBeSplit=1;
		varStackMax=100;
		varQuantityDestroyOnMin=1;
		varQuantityInit=1;
		varQuantityMin=0;
		varQuantityMax=100;
	};
};
